"""The channel's own audio engine: synthesised sound effects, an original music underscore and the
final mixer. Everything here is generated by our code (no samples, no downloads), so the channel
owns the results outright. See README.md in this folder."""
