import raw from "../../../episodes/ep001-enzymes/build/timeline.json";
import type { Timeline } from "../../lib/timeline";

/** Generated by `npm run narrate -- ep001-enzymes && npm run align -- ep001-enzymes`. */
export const TL = raw as unknown as Timeline;

export const sceneById = (id: string) => {
  const s = TL.scenes.find((x) => x.id === id);
  if (!s) throw new Error(`No scene ${id} in timeline`);
  return s;
};
